# Generated by Django 4.2.9 on 2024-03-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_company"),
        ("company", "0001_initial"),
        ("jobs", "0002_company_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Company",
                to="company.company",
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
