# Generated by Django 4.2.9 on 2024-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_company_delete_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="deleted",
        ),
        migrations.AddField(
            model_name="job",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
