# Generated by Django 4.2.9 on 2024-07-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_remove_job_deleted_job_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_link",
            field=models.CharField(max_length=300),
        ),
    ]
