# Generated by Django 4.2.9 on 2024-09-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_dataset_date"),
        ("jobs", "0005_alter_job_job_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="company.company",
            ),
        ),
    ]
