# Generated by Django 4.2.9 on 2025-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_link",
            field=models.CharField(max_length=1000),
        ),
    ]
