# Generated by Django 4.2.9 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
