# Generated by Django 4.2.9 on 2026-03-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_replace_salary_with_min_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
