# Generated by Django 4.2.1 on 2023-12-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0002_city_county_remove_job_job_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_city",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_country",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_county",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_name",
            field=models.TextField(),
        ),
    ]
