# Generated by Django 4.2.1 on 2023-12-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0003_alter_job_job_city_alter_job_job_country_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="County",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_company",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_country",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_county",
            new_name="county",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_name",
            new_name="job_title",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="job_remote",
            new_name="remote",
        ),
    ]
