# Generated by Django 4.2.1 on 2023-12-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0004_delete_city_delete_country_delete_county_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="job_company",
            new_name="company",
        ),
    ]
