# Generated by Django 4.2.1 on 2024-01-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0006_job_edited_job_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="county",
            field=models.TextField(blank=True),
        ),
    ]
