# Generated by Django 4.2.1 on 2024-01-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0007_alter_job_city_alter_job_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
