# Generated by Django 4.2.9 on 2024-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0008_job_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="scname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
