# Generated by Django 4.2.9 on 2024-01-28 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validator", "0009_company_scname_company_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
