# Generated by Django 4.2.9 on 2024-01-28 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("validator", "0010_company_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="User", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
