# Generated by Django 4.2.9 on 2024-01-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0011_alter_company_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
    ]
