# Generated by Django 4.2.9 on 2024-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.TextField(max_length=50)),
                ("scname", models.CharField(blank=True, max_length=50)),
                ("website", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
