# Generated by Django 4.2.9 on 2024-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ManyToManyField(
                blank=True, related_name="Companies", to="company.company"
            ),
        ),
    ]
