# Generated by Django 4.2.9 on 2024-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_delete_testlogs"),
        ("users", "0002_alter_customuser_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="scraper",
            field=models.ManyToManyField(
                blank=True, related_name="Scrapers", to="scraper.scraper"
            ),
        ),
    ]
