# Generated by Django 4.2.9 on 2024-06-03 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('job_wanted', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('searches', models.JSONField(blank=True, default=dict)),
                ('job_type', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid job type', regex='^remote|hybrid|on-site$')])),
            ],
        ),
    ]
