# Generated by Django 4.2.9 on 2024-03-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestLogs",
        ),
    ]
