# Generated by Django 4.2.9 on 2024-03-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_scraperfiles_delete_dataset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScraperFiles",
        ),
    ]
