# Generated by Django 4.2.9 on 2024-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_delete_scraperfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraper",
            name="language",
            field=models.CharField(
                choices=[
                    ("Python", "Python"),
                    ("JavaScript", "JavaScript"),
                    ("Jmeter", "Jmeter"),
                ],
                default="Python",
                max_length=50,
            ),
        ),
    ]
