# Generated by Django 4.2.9 on 2024-09-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_scraper_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraper",
            name="author",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
    ]
